export const EMOJI_OPTIONS = [
  { emoji: "🎨", label: "Seni & Kaligrafi" },
  { emoji: "🖌️", label: "Melukis" },
  { emoji: "🎤", label: "Nasyid & Qiraah" },
  { emoji: "🎵", label: "Musik" },
  { emoji: "🎹", label: "Piano" },
  { emoji: "🎸", label: "Gitar" },
  { emoji: "📖", label: "Membaca & Tahfidz" },
  { emoji: "🕌", label: "Kegiatan Islami" },
  { emoji: "✏️", label: "Menulis" },
  { emoji: "🧮", label: "Matematika" },
  { emoji: "🔬", label: "Sains" },
  { emoji: "🤖", label: "Robotika & Coding" },
  { emoji: "🌍", label: "Pramuka" },
  { emoji: "🥋", label: "Pencak Silat" },
  { emoji: "🏀", label: "Basket" },
  { emoji: "⚽", label: "Sepak Bola & Futsal" },
  { emoji: "🏸", label: "Bulu Tangkis" },
  { emoji: "🏊", label: "Renang" },
  { emoji: "🚴", label: "Bersepeda" },
  { emoji: "🎭", label: "Drama & Teater" },
  { emoji: "📚", label: "Perpustakaan" },
  { emoji: "🧩", label: "Logika & Puzzle" },
  { emoji: "🎯", label: "Fokus & Target" },
  { emoji: "🏆", label: "Prestasi" },
  { emoji: "🎪", label: "Kegiatan Umum" },
  { emoji: "⭐", label: "Unggulan" },
  { emoji: "🏫", label: "Ruang Kelas / Gedung Sekolah" },
  { emoji: "💻", label: "Komputer & Teknologi" },
  { emoji: "🍽️", label: "Kantin" },
  { emoji: "🚐", label: "Antar Jemput / Transportasi" },
];
